### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by yaolp123** [hackerschen/DSNet#1]
Dear author:
   Recently I am interested in reading your project, and I feel this is a great work.  After that, also I have some questions, is that, how could I run this project, I seemly could not find the run script, and how could I find the dataset?  Thank you for your letter, and I am looking forward to your letter.

Dears,
Yao

**Comment by hackerschen** [comment]
We use two parts of the data to build our dataset, the data from the public dataset is already available, the data from the company is under review, and we will make it available when appropriate.
